src/decdk.ts, src/declarative-stack.ts, test/__snapshots__/synth.test.ts.snap, test/errors.test.ts, test/synth.test.ts, test/util.ts
This PR refactors / unifies the parsing logic a little bit, and improves the testing utilities to make it easier to add future unit tests. To demonstrate changes to testing, second part, I added some error handling to check against invalid enum values in deCDK templates, and wrote a unit test for it in `errors.test.ts`.
I've separated most of the changes into smaller commits to make the PR easier to review.
=> chore: refactor deserializeValue and test utilities

README.md, examples/lambda-layer.json, src/deconstruction.ts, test/__snapshots__/synth.test.ts.snap
Instead of relying on a naming convention for Props classes, we use the type
system to reflect the actual type. If the parameter is not present, we omit
deconstructing the properties.
Fixes #76
=> fix: cannot create Constructs without props

src/deconstruction.ts, test/properties.test.ts, test/util.ts
Fixes #8
This was reported as `false` Boolean value failing. Due to the nature of the
broken check, it prevented any falsy values from being translated correctly.
Change also includes additions to the test setup, adding support for fine grained
assertion tests.
=> fix: falsy values do not get translated to properties

examples/apigw.json, examples/lambda-events.json, examples/lambda-handler/index.js, examples/lambda-role-removed.json, examples/lambda-topic.json, test/__snapshots__/synth.test.ts.snap, test/synth.test.ts, test/util.ts
Resolves #164 
Note this changes removes running (some) tests in a temporary working dir. Changing the working directory breaks assumptions about the CWD for file paths. There was no apparent reason why this was introduced in the first place in #110.
There is an open question about how we want to deal with relative file paths. The two options are:
- relative to the CWD
- relative to the template
There is a comment in [deconstruction.ts](https://github.com/cdklabs/decdk/blob/ee07573d61a470288890d14d739dfb88092b51b8/src/deconstruction.ts#L853-L854) that indicates it should be relative to the template file. However the current implementation in [decdk.ts](https://github.com/cdklabs/decdk/blob/145238a53f1f9f8db5c1808500e6bac4c8a0d4a1/src/decdk.ts#L25) does NOT do that (note the missing …
=> chore: fix lambda examples fail with error `ENAMETOOLONG`

src/parser/private/cfn-yaml.ts
> AWS CloudFormation supports the YAML Version 1.1 specification with a few exceptions.
Source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html
=> fix: parser uses unsupported yaml schema

examples/apigw.json, src/parser/schema.ts, src/parser/template/expression.ts
CFN has an undocumented behavior where dot notation shorthand of `Fn::GetAtt` is
supported in JSON template as well. This change add support to handle such scenario.
`yarn build`
Fixes #211
=> fix: `Fn::GetAtt` dot notation shorthand is not supported

test/evaluate/__snapshots__/synth.test.ts.snap, test/util.ts
Disables analytics reporting and the bootstrap version rule when synthesizing test snapshots.
This removes a lot of repetitive noise from the snapshots and makes it easier for a human to parse them, when a diff needs to be investigated.
=> chore: remove noise from test snapshots

examples/method-calls.json, src/parser/template/resource.ts, src/schema/cdk-schema.ts, src/schema/jsii2schema.ts, src/type-resolution/resolve.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/schema/schema.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
`schemaForEnumLikeClass()` already calls `Context.define()`. By calling it again, it led to a cycle, which ultimately resulted in enum like classes not being added to the schema.
This change also relaxes the schema for method calls, accepting any object in the `Call` property. The current implementation generates, for each enum-like class, a schema with all its static methods. But with support for instance calls, this is no longer correct, as the method name will depend on the target of the call, not on the return type. In fact, it may not be possible to create a 100% schema in this case. We can come back to this later and improve the schema, if necessary.
=> fix: generation of enum-like schemas leads to a cyclic reference

test/evaluate/template.test.ts
=> chore: ensure unknown top-level properties don't fail synth

docs/architecture/decisions/0005-custom-intrinsic-to-get-values-from-constructs.md, examples/apigw.json, examples/lambda-policy.yaml, src/evaluate/context.ts, src/evaluate/evaluate.ts, src/evaluate/references.ts, src/parser/template/expression.ts, src/parser/template/resource.ts, src/schema/cdk-intrinsics.ts, src/schema/expression.ts, src/schema/intrinsics.ts, src/type-resolution/references.ts, src/type-resolution/resolve.ts, test/evaluate/intrinsics.test.ts, test/evaluate/references.test.ts, test/parser/intrinsics.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/references.test.ts
Fixes #245 #268
--- 
Contains several changes:
- Refactor Json Schema for Intrinsics to be more dynamic
- Add `CDK::GetProp` JSON schema
- Refactor stack references to be more generic and support different types
- Change `Fn::GetAtt` to always operate on CFN Resources and always return a intrinsic function
- Add `CDK::GetProp` to get Object properties
=> feat: `CDK::GetProp`

examples/method-calls.json, src/evaluate/evaluate.ts, src/parser/template/resource.ts, src/type-resolution/callables.ts, src/type-resolution/enums.ts, src/type-resolution/resource-like.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/callables.test.ts
Making the type optional for lazy resources (defined by method calls). It will be inferred from the return type of the method. For instance methods, it's necessary to recursively look up the the type of the "factory resource" first. On this dependency chain, the type can be omitted on multiple resources and the lookup will stop at a base case.
For eager resources (defined by properties), the type declaration remains mandatory.
=> feat: type inference

src/schema/intrinsics.ts, test/evaluate/intrinsics.test.ts
Note that `Fn::Select` will **never** return a Construct object. Instead `Ref` will always return the ref to the default child.
Doing otherwise doesn't make a lot of sense, since there are two general cases with FnSelect:
- The index is a known value
- The index is only resolved server-side
In the first case of a known index, a user can just self-select and remove the select intrinsic.
In the second case of server-side resolution, we cannot represent the Construct anymore, so there is no point in attempting to reference it.
=> feat: FnSelect

src/evaluate/references.ts, test/evaluate/intrinsics.test.ts, test/util.ts
It's possible to break the app accessing stack directly. Best to just prevent it.
=> fix: FnGetProp can access underlying stack details

src/parser/private/types.ts, src/parser/template/mappings.ts, src/parser/template/resource.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/evaluate/template.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
Given the following template:
```yaml
Mappings:
RegionMap:
us-west-1:
HVM64: ami-0bdb828fd58c52235
```
This previously resulted in this template:
```yaml
Mappings:
RegionMap:
us-west-1:
HVM64:
- ami-0bdb828fd58c52235    # <--- This should not be a list
```
Now correctly keeps the Mapping value as string.
=> fix: all Mappings are incorrectly lists

src/parser/template/parameters.ts, test/evaluate/template.test.ts, test/util.ts
[Sample Templates in the CFN docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-sample-templates.html#w2ab1c31c28c21c31b5) are using strings for Paramters.
=> fix: allow and test `'true'` in `NoEcho`, explicitly test string to number conversion

examples/application-load-balancer.yaml, src/evaluate/evaluate.ts, src/parser/template/expression.ts, src/schema/jsii2schema.ts, src/type-resolution/callables.ts, src/type-resolution/expression.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
Creates a new type in the AST, `null`, which will be interpreted as an empty list in case of method and constructor parameters.
=> feat: allow null to indicate an empty args list

.gitignore, .projenrc.ts, examples/apigw.json, examples/lambda-topic.json, examples/pure-cfn.json, src/evaluate/evaluate.ts, src/evaluate/outputs.ts, src/parser/template/index.ts, src/type-resolution/expression.ts, src/type-resolution/template.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/evaluate/template.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
Fixes https://github.com/cdklabs/decdk/issues/249
Note:
A new construct of CfnOutput is created because:
1. In cdk lib, `output.value` is set to a string in [OutputProp](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/core/lib/cfn-output.ts#L18).
2. Type of `Condition` is `CfnCondition` while in decdk, we can treat it as a string.
=> feat: support outputs in template

src/schema/jsii2schema.ts, src/type-resolution/resolve.ts, src/type-system/interfaces.ts, test/evaluate/template.test.ts, test/type-system/interfaces.test.ts
Enables cyclic references in JsonSchema. I did a check on the additional Schemas and there was no reason why these should not be included. Cyclic refs are allowed in JsonSchema. We can assume any cycle can be resolved correctly due to the data coming form CDK, i.e. all cyclic references will eventually end in an optional property thus breaking the loop in user land.
While adding an evaluation test, an issue emerged with classes starting with `I` being wrongly resolved as behavioral interface, as well as classes not being resolved if they didn't fit any of the other more narrow categories. This was tested and fixed as well.
=> feat: allow cyclic types in schema

examples/http-proxy.yaml, src/type-resolution/callables.ts, src/type-resolution/resolve.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/callables.test.ts, test/util.ts
Conversion of
https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/http-proxy-apigateway and required fixes.
Note that I have adjusted the example to be more declarative and moved the edge-cases of a direct translation to unit tests.
=> fix: allow class implementations when expected type is a class, not only when it's an interface

src/parser/private/cfn-yaml.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts, test/parser/yaml.test.ts
fix: dates are parsed as date object, not string
fix: unquoted `.` is parsed as float, not string
--- 
Cause for the issue with unquoted `.` is that the regex for float has a bug that causes `.` to be considered a float. This is actually a bug in the yaml spec as well (or maybe even intentional). 
I decided to add a new tag for unquoted `.`. This seemed to be the least invasive.
However, I'm not entirely convinced it's the best approach to effectively just add a special.
Alternatives are as follow. Aside from fixing the regex, this basically means dropping the float parsing from the yaml parser and doing it ourselves. Which we might not be doing exactly to YAML spec.
- Attempt to patch the buggy regex and replace it with one like this: `/^[-+]?(?:[0-9][0-9_]*\.[0-9_]*|\.[0-9_]+)$/` \ …
=> fix: yaml not parsing certain values as string

cloudformation.schema.json, src/parser/template/template.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts
We don't enforce templates to be useful, e.g. Resources could have been empty. So let's not limit ourselves with this.
=> fix: `Resources` should be required in template

src/parser/private/sub.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts, test/parser/sub.test.ts
--- 
Template simplified for brevity.
```json
{
"Resources": {
"Bucket": {
"Type": "AWS::IAM::Role",
"Properties": {
"Description": { "Fn::Sub": "${!NoSpace}${ ! BothSpace}${! AfterSpace}${ !BeforeSpace}${!EndSpace }" },
}
}
}
}
```
=> fix: spaces in FnSub literals are causing value to not be a literal

src/parser/template/policies.ts, test/evaluate/resource.test.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap, test/util.ts
Also includes a small fix to the schema errors in tests if a resource type cannot be found.
=> fix: `StartFleet` CreationPolicy not supported

src/evaluate/evaluate.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts, test/evaluate/references.test.ts, test/evaluate/template.test.ts
=> fix: Resources and other types (Conditions, Outputs, etc) cannot have the same name

README.md, examples/application-load-balancer.yaml, examples/lambda-dashboard.yaml, examples/static-site.yaml, src/parser/schema.ts, src/parser/template/calls.ts, src/parser/template/resource.ts, src/schema/cdk-schema.ts, src/schema/jsii2schema.ts, src/type-resolution/callables.ts, src/type-resolution/resource-like.ts, test/evaluate/references.test.ts, test/evaluate/resource.test.ts, test/evaluate/template.test.ts, test/fixtures/templates/syntax-method-calls.json, test/fixtures/templates/syntax-short-intrinsics.yaml, test/schema/schema.test.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap, test/type-resolution/callables.test.ts, test/type-resolution/fixtures.test.ts
Change the method call syntax to:
```yaml
BucketPermissions:
Type: aws-cdk-lib.aws_iam.Grant
Call:
- MyBucket.nested 
- grantRead: 'files/*'
BucketPermissions:
Type: aws-cdk-lib.aws_iam.Grant
Call:
- aws-cdk-lib.aws_s3.Bucket.fromBucketName: 'files/*'
BucketPermissions:
Type: aws-cdk-lib.aws_iam.Grant
Call:
aws-cdk-lib.aws_s3.Bucket.fromBucketName: 'files/*'   
```
In a nutshell: `parseCall` now inspects the value of the `Call` property and returns a more structured data type, `FactoryMethodCall`. As a result, type resolution has become simpler (a couple of methods were removed).
Closes https://github.com/cdklabs/decdk/issues/345.
=> feat: new call syntax

src/parser/template/expression.ts, src/type-resolution/callables.ts, src/type-resolution/enums.ts, src/type-resolution/expression.ts, src/type-resolution/resolve.ts, test/evaluate/errors.test.ts
Fixes #62
---
Wrong type:
```
Old: Error: Expected object, got: {"type":"string","value":"MyBucket"}
New: TypeError: Expected aws-cdk-lib.aws_s3.IBucket, got: "MyBucket"
```
Static Method not found:
```
Old: Error: Assembly "" not found
New: TypeError: Expected static method not found, got: "bucket"
```
=> fix: provide useful type resolution errors

src/decdk-schema.ts, src/schema/cdk-schema.ts, src/schema/jsii2schema.ts
Suppresses 3 warnings about legitimately incompatible interfaces. We should not display these warnings to users.
Also improves the usefullness of warnings. In some cases the provided context/name was skipping important info.
Finally, removes the (empty) schema for methods that are not schematizable.
Releated to #63 
----
Was:
```
[impl "aws-cdk-lib.SecretValue"]
[method "any"]
didn't match any schematizable shape
cannot schematize method because parameter cannot be schematized
```
Now:
```
[impl "aws-cdk-lib.SecretValue"]
[method "aws-cdk-lib.Lazy.any"]
[param "producer"]
didn't match any schematizable shape
cannot schematize method because parameter cannot be schematized
```
=> chore: suppress schema warnings for legitimate incompatible interfaces

package.json, src/declarative-stack.ts, src/evaluate/evaluate.ts, src/parser/template/template.ts, src/type-resolution/template.ts, test/evaluate/template.test.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap, yarn.lock
This will avoid name clashes with CloudFormation in the future, in case they decide to add a new top-level section with the same name.
=> feat: CDK context moved to the `Metadata` section.

.projen/deps.json, .projenrc.ts, package.json, src/util.ts
Changes `aws-cdk-lib` to be a peer dependency with very loose version constraint and then adds it as a dev depdendency with tight version constraint.
The change to the schema are changes in ordering only.
Fixes #351 in the sense that decdk now doesn't limit versions of aws0cdk core anymore.
=> chore: aws-cdk-lib as peer dependency so consumers can define their own version

src/decdk.ts, src/declarative-stack.ts, src/error-handling/annotations.ts, src/error-handling/errors.ts, src/error-handling/index.ts, src/error-handling/unparse.ts, src/evaluate/context.ts, src/evaluate/errors.ts, src/evaluate/evaluate.ts, src/evaluate/references.ts, src/parser/private/types.ts, src/parser/template/calls.ts, src/parser/template/expression.ts, src/parser/template/overrides.ts, src/type-resolution/expression.ts, src/type-resolution/primitives.ts, src/type-resolution/references.ts, src/type-resolution/union.ts, test/evaluate/errors.test.ts
Resolves first part of #410 
Laying the groudwork and collect evaluation errors.
---
Creates errors like below. Note that the formatting is not final. We should probably do some tree based output.
The errors can also be inspected programatically.
```
DeclarativeStackError:
[RuntimeError at Resources.SiteDistribution]
Cannot read properties of undefined (reading 'bind')
[TypeError at Resources.SiteDistribution.Properties.defaultBehavior.origin."aws-cdk-lib.aws_cloudfront_origins.S3Origin"]
Cannot read properties of undefined (reading 'isWebsite')
[RuntimeError at Resources.SiteDistribution.Properties.defaultBehavior.origin."aws-cdk-lib.aws_cloudfront_origins.S3Origin".0.Ref]
No such Resource or Parameter: SiteCertificate
[RuntimeError at …
```
=> feat: collect errors

examples/http-proxy.yaml, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/type-resolution/__snapshots__/fixtures.test.ts.snap
Previous version failed with an API gateway error. Also adds support for proxying the root and changes the default url to a more proxy friendly example.
=> fix: http-proxy doesn't deploy

src/declarative-stack.ts, src/parser/private/toposort.ts, src/type-resolution/callables.ts, src/type-resolution/resolve.ts, src/type-resolution/resource-like.ts, src/type-resolution/template.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap, test/type-resolution/callables.test.ts
Adds a context to type resoltion. Currently making use of it to access the in progress TypedTemplate, which made for a nice refactor of `inferType`. In future will be used to collect errors.
=> chore: refactor type-resolution to use context

src/declarative-stack.ts, src/evaluate/context.ts, src/evaluate/evaluate.ts, src/index.ts, src/type-resolution/index.ts, src/type-resolution/template.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap
Adds and exports an abstract `BaseEvaluator` that should make custom implementations much easier.
Also fixes some inconsistencies with features not implemented inside the compiler structure, as defined in [ADR-0007](https://github.com/cdklabs/decdk/blob/57bb22a5d09570f05a09187c3398bb6c68e632d9/docs/architecture/decisions/0007-compiler-stages.md#L1)
=> chore: make lower-level features more extensible
