.projen/tasks.json, .projenrc.ts, src/deconstruction.ts, src/jsii2schema.ts, src/parser/private/toposort.ts, src/parser/private/types.ts, src/parser/template/expression.ts, src/type-resolution/callables.ts, src/type-resolution/collections.ts, src/type-resolution/enums.ts, src/type-resolution/expression.ts, src/type-resolution/index.ts, src/type-resolution/literals.ts, src/type-resolution/primitives.ts, src/type-resolution/references.ts, src/type-resolution/resolve.ts, src/type-resolution/resource-like.ts, src/type-resolution/struct.ts, src/type-resolution/union.ts, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/callables.test.ts, test/type-resolution/collections.test.ts, test/type-resolution/enums.test.ts, test/type-resolution/examples.test.ts, test/type-resolution/references.test.ts, test/type-resolution/resolve.test.ts, test/type-resolution/resource.test.ts, test/util.ts
Adding a type resolver that checks and amends the parsed AST with types.
This doesn't cover any improvements to references yet that we have discussed. But should be on par with the current implementation and I'd rather iterate on it.
=> feat: resolve types in AST

src/evaluate/context.ts
=> chore: refactor reference records in evaluation context

src/evaluate/evaluate.ts, test/references.test.ts
=> fix: unable to reference construct in cloudformation resource

src/declarative-stack.ts, src/evaluate/context.ts, src/evaluate/evaluate.ts, src/type-resolution/template.ts
Fixes @otaviomacedo feedback on #208
=> chore: refactor type evaluation into a distinct step

cdk.schema.json, examples/apigw.json, examples/ecs.json, examples/lambda-events.json, examples/lambda-layer.json, examples/lambda-role-removed.json, examples/lambda-topic.json, examples/pipeline.json, src/schema/jsii2schema.ts, src/type-resolution/callables.ts, test/schema/failures.test.ts, test/type-resolution/callables.test.ts, test/type-resolution/collections.test.ts, test/type-resolution/references.test.ts
=> feat: only allow FQNs in static method calls

examples/fleet.json, src/parser/private/types.ts, src/type-resolution/callables.ts, src/type-resolution/expression.ts, src/type-resolution/resolve.ts, src/type-resolution/types.ts, test/__snapshots__/synth.test.ts.snap, test/schema/fixture/.jsii, test/schema/fixture/index.ts, test/schema/schema.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/callables.test.ts
Fixes: #50
---
**Review by commit**
Note that the second commit (schema test) is entirely irrelevant to the fix. I had written it to investigate my initial thought about what the issue would be. Yay, free test!
=> fix: cannot pass `EcsOptimizedImage` to `IMachine` parameter in contruct

docs/architecture/decisions/0003-types-and-properties-use-jsii-nomenclature.md, docs/architecture/decisions/0004-use-only-fully-qualified-names.md
=> chore: document naming decisions

examples/lambda-policy.yaml, src/evaluate/evaluate.ts, src/type-resolution/expression.ts, src/type-resolution/references.ts, src/type-resolution/resolve.ts, test/evaluate/__snapshots__/references.test.ts.snap, test/evaluate/__snapshots__/synth.test.ts.snap, test/evaluate/references.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/references.test.ts, test/util.ts
Fixes #243 
---
Note: Keeps the behaviour `FnGetAtt` the same for now because of changes expected from #245
=> feat: resolve references only when explicitly needed

src/evaluate/evaluate.ts, src/parser/template/expression.ts, src/parser/template/resource.ts, src/schema/conditions.ts, src/schema/intrinsics.ts, test/evaluate/intrinsics.test.ts
Feature complete implementation for:
- Fn::Base64
- Fn::Cidr
- Fn::GetAZs
- Fn::ImportValue
Includes fixes to Fn::Select & Fn::GetAtt but these might not be final (although probably close now)
=> feat: fully implement Fn::Base64, Fn::Cidr, Fn::GetAZs, Fn::GetAZs

src/evaluate/evaluate.ts, src/parser/template/expression.ts, src/parser/template/resource.ts, src/schema/expression.ts, src/schema/intrinsics.ts, test/evaluate/intrinsics.test.ts, test/schema/intrinsics.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
Feature complete implementation for:
- Fn::Join
- Fn::Split
- Fn::Sub
=> feat: fully implement Fn::Join, Fn::Split, Fn::Sub

src/evaluate/evaluate.ts, src/evaluate/references.ts, src/parser/template/expression.ts, test/evaluate/intrinsics.test.ts
=> feat: support dot notation for nested properties on FnGetProp

examples/method-calls.json, src/schema/jsii2schema.ts, src/type-resolution/callables.ts, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/callables.test.ts
Users can declare method calls by passing an array or arguments in the right order.
Fixes https://github.com/cdklabs/decdk/issues/264.
=> feat: positional arguments

examples/ec2-instance.yaml, src/evaluate/evaluate.ts, src/parser/template/mappings.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/evaluate/intrinsics.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
=> feat: Mappings

cloudformation.schema.json, examples/bucket-with-parameters.json, src/evaluate/evaluate.ts, src/parser/template/parameters.ts, src/parser/template/template.ts, src/type-resolution/template.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/evaluate/template.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
=> feat: support Parameters

examples/apigw.json, examples/application-load-balancer.yaml, examples/ecs.json, examples/fleet.json, examples/lambda-events.json, examples/lambda-layer.json, examples/lambda-policy.yaml, examples/lambda-role-removed.json, examples/lambda-topic.json, examples/pipeline.json, src/schema/jsii2schema.ts, src/type-resolution/callables.ts, test/evaluate/intrinsics.test.ts, test/evaluate/references.test.ts, test/evaluate/resource.test.ts, test/schema/intrinsics.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap, test/type-resolution/callables.test.ts, test/type-resolution/collections.test.ts, test/type-resolution/intrinsics.test.ts, test/type-resolution/references.test.ts
Fixes https://github.com/cdklabs/decdk/issues/303
=> fix: dropped support for keyword arguments

src/schema/cdk-schema.ts, src/schema/jsii2schema.ts, src/type-resolution/callables.ts, src/type-resolution/resolve.ts, src/type-system/construct.ts, src/type-system/enums.ts, src/type-system/implements.ts, src/type-system/index.ts, src/type-system/interfaces.ts, src/type-system/serializable.ts, test/schema/schema.test.ts, test/util.ts
- Mostly moving files around into separate modules.
- Fixes a few small performance issues where methods were called unnecessarily (ca. 5% improvement on my machine)
- Adds support for resource level schema errors in tests.
=> chore: refactor schema generator

examples/cfn-policies.yaml, package.json, src/evaluate/evaluate.ts, src/parser/template/policies.ts, src/parser/template/resource.ts, src/type-resolution/resource-like.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/type-resolution/__snapshots__/examples.test.ts.snap, yarn.lock
CFN resources and CDK constructs now have separate initialization functions.
=> feat: CreationPolicy is passed through to the output template

examples/cfn-policies.yaml, src/evaluate/evaluate.ts, src/type-resolution/resource-like.ts, test/evaluate/__snapshots__/references.test.ts.snap, test/evaluate/__snapshots__/synth.test.ts.snap, test/type-resolution/__snapshots__/examples.test.ts.snap
Fixes https://github.com/cdklabs/decdk/issues/236
=> feat: DeletionPolicy, UpdateReplacePolicy and Metadata are passed through to the output template

examples/queue-kms.json, src/evaluate/evaluate.ts, src/parser/schema.ts, src/parser/template/template.ts, src/parser/template/transform.ts, src/type-resolution/template.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/type-resolution/__snapshots__/examples.test.ts.snap
Fixes https://github.com/cdklabs/decdk/issues/278
=> feat: Support for the Transform section

examples/pure-cfn.json, src/evaluate/evaluate.ts, src/type-resolution/template.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/evaluate/template.test.ts, test/type-resolution/__snapshots__/examples.test.ts.snap
=> feat: Support conditions section

examples/lambda-dashboard.yaml, examples/lambda-policy.yaml, src/evaluate/evaluate.ts, test/evaluate/__snapshots__/synth.test.ts.snap, test/type-resolution/__snapshots__/examples.test.ts.snap
=> feat: test yaml short form support

test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts, test/fixtures/templates/cloudformation/if-in-tags.json, test/fixtures/templates/cloudformation/outputs-with-references.json
chore: description cannot be a reference
chore: fix fixture for if in tags
=> chore: fix issues with template fixtures

src/evaluate/evaluate.ts, src/parser/template/expression.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap
Fixes https://github.com/cdklabs/decdk/issues/366
=> fix: FindInMap doesn't accept references as the value of mappingName

cloudformation.schema.json, package.json, src/schema/cdk-schema.ts, src/schema/rules.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/fixtures/templates/cloudformation/only-parameters-and-rule.json, yarn.lock
Closes https://github.com/cdklabs/decdk/issues/342.
=> chore: add schema for rule specific intrinsics

src/evaluate/evaluate.ts, src/parser/template/transform.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts, test/evaluate/template.test.ts
Fixes https://github.com/cdklabs/decdk/issues/370.
=> fix: transforms with parameters are not accepted

cloudformation.schema.json, src/evaluate/evaluate.ts, src/parser/schema.ts, src/parser/template/hooks.ts, src/parser/template/template.ts, src/type-resolution/template.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/fixtures.test.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap
Closes https://github.com/cdklabs/decdk/issues/362.
=> feat: support for hooks

src/declarative-stack.ts, src/parser/schema.ts, src/parser/template/template.ts, test/evaluate/template.test.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap
Closes https://github.com/cdklabs/decdk/issues/191.
=> feat: support for CDK context

src/evaluate/evaluate.ts, src/parser/template/expression.ts, src/parser/template/resource.ts, src/schema/intrinsics.ts, test/evaluate/__snapshots__/fixtures.test.ts.snap, test/evaluate/intrinsics.test.ts, test/type-resolution/__snapshots__/fixtures.test.ts.snap
These functions were being skipped by the parser.
=> fix: Fn::ToJsonString and Fn::Length don't work inside a CDK construct
